### ISSUE TITLE
Support for Tor proxy

### ISSUE THREAD

**Issue by ibudisteanu** [PandoraPay/pandorapay-electron-js#2]
Maybe users might have Tor installed on their computers. The app should be able to accept Tor proxys

**Comment by yuansong862** [comment]
Check https://github.com/yuansong862/pandorapay-electron-js/commit/dbce2ebce35d9fa82ea1d227b896c5b4aa918970

**Comment by ibudisteanu** [comment]
I merged your latest commits. Thanks
